version: '3.7'

services:
  milvus:
    image: milvusdb/milvus:v2.3.1
    container_name: milvus
    environment:
      ETCD_ENDPOINTS: etcd:2379
    ports:
      - "19530:19530"
    volumes:
      - milvus_data:/var/lib/milvus
    restart: always

volumes:
  milvus_data:
